name: daeja
description: "전국 주차장 정보를 실시간으로 확인할 수 있는 앱"

version: 1.2.9+40

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  ### M A P ###
  geolocator: ^14.0.2
  flutter_naver_map: ^1.4.4
  map_launcher: ^4.4.2

  ### 상태 관리 ###
  flutter_riverpod: ^3.0.3

  ### 데이터 베이스 ###
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_dotenv: ^6.0.0

  ### 네트워크 요청 ###
  dio: ^5.9.0

  ### F I R E B A S E ###
  firebase_core: ^4.2.1
  cloud_firestore: ^6.1.0
  firebase_auth: ^6.1.2
  firebase_messaging: ^16.1.0
  flutter_local_notifications: ^19.5.0

  ### U T I L ###
  velocity_x: ^4.3.1
  flutter_animate: ^4.5.2
  intl: ^0.20.2
  intl_phone_number_input: ^0.7.5
  webview_flutter: ^4.13.1
  url_launcher:
  flutter_svg: ^2.2.3
  speech_to_text: ^7.0.0
  app_settings: ^7.0.0


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app-icon.png"
  adaptive_icon_background: "#6D9BC3"
  adaptive_icon_foreground: "assets/icons/app-icon.png"
  remove_alpha_ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  # 앱 아이콘 생성 도구
  flutter_launcher_icons: ^0.14.4

flutter:

  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/icons/
    - assets/terms/
    - assets/images/cars/
