// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5TVOgiJR8wGdeoZzM-HYBdp7gfxlNGrU',
    appId: '1:701371078920:web:ae457ad365fa98a263f4bd',
    messagingSenderId: '701371078920',
    projectId: 'daeja-a9909',
    authDomain: 'daeja-a9909.firebaseapp.com',
    storageBucket: 'daeja-a9909.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFZq9tT_Hx3uclVTptjLRcl1UXJ3yueNk',
    appId: '1:701371078920:android:e3a5e95714aeecf463f4bd',
    messagingSenderId: '701371078920',
    projectId: 'daeja-a9909',
    storageBucket: 'daeja-a9909.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDq45IVtYh1im8_iHHdW_D5-Uk-eB1uMoI',
    appId: '1:701371078920:ios:46fa50ba8f372fc463f4bd',
    messagingSenderId: '701371078920',
    projectId: 'daeja-a9909',
    storageBucket: 'daeja-a9909.firebasestorage.app',
    iosBundleId: 'com.ceyhun.daeja',
  );

}